### ISSUE TITLE
Sprint 2: Planejamento da Sprint 2

### ISSUE THREAD

**Issue by julianoAlessandro** [gabrielalmir/tethys#2]
- [x] Definição de objetivos
- [x] Seleção de Histórias
- [x] Elaboração de Histórias
- [x] Estimativas
- [x] Definição das tarefas técnicas
- [x] Realizar tarefas de código da Sprint

**Comment by gabrielalmir** [comment]
Celso & Gustavo:
- [ ] Criação de tela de login
- [ ] Criação de tela de cadastro
- [ ] Criação de tela do perfil do usuário (extra)
- [ ] Criação de página principal

Rafael:
- [ ] Criar classe ou função para envio de SMS via Twillio
- [ ] Integrar a funcionalidade de envio de SMS via API com [FastAPI](https://fastapi.tiangolo.com/)

Juliano:
- [ ] Criar classe ou função para obter dados de API climática
- [ ] Integrar a funcionalidade de pedidos da API com [FastAPI](https://fastapi.tiangolo.com/)

**Comment by cwilliam956** [comment]
Criação das telas realizadas
