### ISSUE TITLE
Sprint 2: Atualizar projeto com as informações anteriores sobre o projeto

### ISSUE THREAD

**Issue by gabrielalmir** [gabrielalmir/tethys#3]
Mais algumas tarefas para realizar pontualmente para Sprint 2:
- [x] Atualizar o README.md para seguir de acordo com o README proposto em https://github.com/julianoAlessandro/PI3-AlertaAlagamento.
- [x] Inserir pastas: "frontend", "backend" e "docs" na raiz do projeto
- [x] A pasta de backend deverá pastas para cada microserviço adicionado (sempre letra minúscula, sem espaços, sem caracteres especiais) ex: api-indice-pluviometrico

**Comment by julianoAlessandro** [comment]
observando vai faltar os micro serviços dos demais integrantes

**Comment by gabrielalmir** [comment]
Podemos adicionar os microserviços em subpastas em backend.
